site_name: 3MS
site_url: https://3ms.3dcoded.xyz/
repo_url: https://github.com/3dcoded/3MS
plugins:
  - search
  - macros
  - step_helper
  - redirects:
      redirect_maps:
        'instructions/software-setup.md': 'https://github.com/moggieuk/Happy-Hare/wiki/Quick-Start-3MS'
  # - spellcheck:
  #     backends:
  #     - symspellpy
  #     - codespell
  #     ignore_code: yes
  #     known_words: known_words.txt
  - autolinks
  # - git-revision-date-localized:
      # enable_creation_date: true
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deustch
          build: true
          nav_translations:
            Home: Startseite
            # Comparison of Multimaterial Systems: Vergleich verschiedener automatisierter Filamentwechsler
            Setup: Einrichten
            BOM: St√ºckliste
            Controllers: Kontrollboards
            Archive: Archiv
            Guides: Guides
            Contributing: Mitwirken
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - print-site:
      path_to_pdf: export.pdf
markdown_extensions:
  - neoteroi.timeline
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: false
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
extra:
  analytics:
    provider: google
    property: G-ERRF9DWVTD
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ekqxDhdGCg
      name: Discord
    - icon: fontawesome/brands/github
      link: https://github.com/3DCoded/3MS
      name: GitHub
  status:
    new: Recently added
    updated: Recently updated
    deprecated: Deprecated
copyright: Copyright &copy; 2024-2025 Christopher Mattar (3DCoded)
theme:
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: docs/overrides
  features:
      - navigation.indexes
      - navigation.footer
      - navigation.expand
      - navigation.instant
      - navigation.top
      - navigation.sections
      - navigation.instant.prefetch
      - search.suggest
      - search.highlight
      - search.share
      - content.tooltips
      - content.code.copy
      - content.tabs.link
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
hooks:
  - hooks.py
nav:
  - Home: index.md
  - compare.md
  - tips.md
  - Instructions:
    - instructions/index.md
    - BOM: instructions/bom.md
    - Printed Parts & Tools: instructions/printed-parts-and-tools.md
    - Hardware Assembly: instructions/hardware-assembly.md
    - Electronic Assembly: instructions/electronic-assembly.md
    - Final Assembly: instructions/final-assembly.md
    - Software Setup: instructions/software-setup.md
    - Configuration: instructions/config.md
    - Calibration: instructions/calibration.md
    - First Print: instructions/firstprint.md
  - Other Boards:
    - controllers/index.md
    - controllers/skrpico.md
    - controllers/index.md
    - controllers/bttmmb.md
    - controllers/skrminie3v2.md
    - controllers/bttoctopusmain.md
    - controllers/einsyrambo-skrminie3v2.md
    - controllers/zm384main.md
    - controllers/minirambo.md
    - controllers/mellowflyd7.md
    - controllers/geetech-a30t.md
  - Kits:
    - kits/index.md
    - Tour: kits/tour.md
  - Guides:
    - Printers:
      - Creality K1/E3v3 Series: guides/printers/creality.md
    - guides/generator.md
    - guides/steppercurrent.md
  - Contributing:
    - contributing/index.md
    - contributing/devsetup.md

extra_css:
  - stylesheets/extra.css
  - assets/css/calibration.css
  - assets/css/neoteroi-mkdocs.css

extra_javascript:
  - assets/javascript/calibration.js